/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.unipampa.frames;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import org.unipampa.categorias.Apartamento;
import org.unipampa.categorias.Imovel;
import org.unipampa.crud.ListaImoveisCrud;

/**
 *
 * @author Lucascorrea
 */
public class ApartamentoFrame extends javax.swing.JFrame {

    //private List<Imovel> listaApartamento;
    private ListaImoveisCrud listaApartamento;
    private int aux;

    /**
     * Creates new form ApartamentoFrame
     */
    public ApartamentoFrame(ListaImoveisCrud listaApartamento) {
        initComponents();
        this.setLocationRelativeTo(null);
        
        this.listaApartamento = listaApartamento;

        jTabbedPane1.setEnabledAt(1, false);
        jButtonDetalhes.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonEditar.setEnabled(false);

    }

    //<editor-fold defaultstate="collapsed" desc="Método Listar">
    public void listar(int cod, boolean isPesquisa) {
        DefaultListModel modelList = new DefaultListModel();

        if (isPesquisa) {
            Imovel apartamento = listaApartamento.consultar(cod);
            if (apartamento == null) {
                JOptionPane.showMessageDialog(null, "Imóvel não encontrado");
            } else {
                modelList.addElement(apartamento.toString());
            }
        } else {
            List<Imovel> apt = listaApartamento.getLista();
            for (Imovel apartamento : apt) {
                modelList.addElement(apartamento.toString());
            }
        }

        jList.setModel(modelList);
    }
    //</editor-fold>

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList = new javax.swing.JList<>();
        jButtonIncluirApartamento = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextCodigo = new javax.swing.JTextField();
        jButtonListar = new javax.swing.JButton();
        JButtonVoltarMenuPrincipal = new javax.swing.JButton();
        jButtonDetalhes = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLogradouro = new javax.swing.JTextField();
        jNro = new javax.swing.JTextField();
        jCidade = new javax.swing.JTextField();
        jAreaTotal = new javax.swing.JTextField();
        jValor = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jDescricao = new javax.swing.JTextPane();
        jButtonSalvar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jNomeEdificio = new javax.swing.JTextField();
        jAnoContrucao = new javax.swing.JTextField();
        jNroApt = new javax.swing.JTextField();
        jAndar = new javax.swing.JTextField();
        jNroQuartos = new javax.swing.JTextField();
        jNroVagas = new javax.swing.JTextField();
        jBairro = new javax.swing.JTextField();
        jValorCondominio = new javax.swing.JTextField();
        jEditar = new javax.swing.JButton();
        jLabelCodigo = new javax.swing.JLabel();
        jCodigo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Apartamentos");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList);

        jButtonIncluirApartamento.setText("Incluir");
        jButtonIncluirApartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirApartamentoActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Código:");

        jTextCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextCodigoKeyTyped(evt);
            }
        });

        jButtonListar.setText("Listar");
        jButtonListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarActionPerformed(evt);
            }
        });

        JButtonVoltarMenuPrincipal.setText("Voltar");
        JButtonVoltarMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonVoltarMenuPrincipalActionPerformed(evt);
            }
        });

        jButtonDetalhes.setText("Detalhes");
        jButtonDetalhes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDetalhesActionPerformed(evt);
            }
        });

        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonIncluirApartamento, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(jButtonExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JButtonVoltarMenuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(jButtonDetalhes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextCodigo)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonListar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(244, 244, 244))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonListar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonIncluirApartamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonDetalhes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonExcluir)
                        .addGap(27, 27, 27)))
                .addComponent(JButtonVoltarMenuPrincipal)
                .addGap(133, 133, 133))
        );

        jTabbedPane1.addTab("Menu", jPanel1);

        jPanel2.setPreferredSize(new java.awt.Dimension(674, 350));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Logradouro:");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Nº:");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Bairro:");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Cidade:");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Descrição:");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("Área Total:");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("Valor:");

        jLogradouro.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jNro.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jNro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jNroKeyTyped(evt);
            }
        });

        jCidade.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jAreaTotal.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jAreaTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jAreaTotalKeyTyped(evt);
            }
        });

        jValor.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jValorKeyTyped(evt);
            }
        });

        jDescricao.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(jDescricao);

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Voltar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("N° de Quartos:");

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setText("N° Vagas Garagem:");

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setText("Ano Contrução:");

        jLabel14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel14.setText("Nome do Edifício");

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setText("Andar: ");

        jLabel16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel16.setText("N° Apartamento:");

        jLabel17.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel17.setText("Valor Condomínio: ");

        jNomeEdificio.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jAnoContrucao.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jAnoContrucao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jAnoContrucaoKeyTyped(evt);
            }
        });

        jNroApt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jNroApt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jNroAptKeyTyped(evt);
            }
        });

        jAndar.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jAndar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jAndarKeyTyped(evt);
            }
        });

        jNroQuartos.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jNroQuartos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jNroQuartosKeyTyped(evt);
            }
        });

        jNroVagas.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jNroVagas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jNroVagasKeyTyped(evt);
            }
        });

        jBairro.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jValorCondominio.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jValorCondominio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jValorCondominioKeyTyped(evt);
            }
        });

        jEditar.setText("Editar");
        jEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEditarActionPerformed(evt);
            }
        });

        jLabelCodigo.setText("Código: ");

        jCodigo.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jNro, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLogradouro))
                        .addGap(32, 39, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(jValor, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jAreaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jNomeEdificio, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jNroVagas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelCodigo)
                                .addGap(213, 213, 213))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel17)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jNroApt, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel15)))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jValorCondominio, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jAndar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jNroQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel12))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jAnoContrucao, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel16)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10)
                    .addComponent(jValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jNro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAreaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jNomeEdificio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jValorCondominio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(jAnoContrucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jNroApt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15)
                        .addComponent(jAndar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jNroQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jNroVagas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCodigo)
                    .addComponent(jCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonSalvar)
                    .addComponent(jEditar))
                .addGap(19, 19, 19))
        );

        jTabbedPane1.addTab("Dados", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
        jTabbedPane1.setEnabledAt(0, true);
        jTabbedPane1.setEnabledAt(1, false);
        jButtonSalvar.setVisible(true);

        //<editor-fold defaultstate="collapsed" desc="Liberar Campos">
        jNroQuartos.setEnabled(true);
        jAndar.setEnabled(true);
        jCidade.setEnabled(true);
        jLogradouro.setEnabled(true);
        jNro.setEnabled(true);
        jBairro.setEnabled(true);
        jDescricao.setEnabled(true);
        jAreaTotal.setEnabled(true);
        jValor.setEnabled(true);
        jNroQuartos.setEnabled(true);
        jNroVagas.setEnabled(true);
        jAnoContrucao.setEnabled(true);
        jNomeEdificio.setEnabled(true);
        jAndar.setEnabled(true);
        jValorCondominio.setEnabled(true);
        jNroApt.setEnabled(true);
        //</editor-fold>

        //<editor-fold defaultstate="collapsed" desc="Limpar Campos">
        jNroQuartos.setText("");
        jAndar.setText("");
        jCidade.setText("");
        jLogradouro.setText("");
        jNro.setText("");
        jBairro.setText("");
        jDescricao.setText("");
        jAreaTotal.setText("");
        jValor.setText("");
        jNroQuartos.setText("");
        jNroVagas.setText("");
        jAnoContrucao.setText("");
        jNomeEdificio.setText("");
        jAndar.setText("");
        jValorCondominio.setText("");
        jNroApt.setText("");
        //</editor-fold>


    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonIncluirApartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirApartamentoActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
        jTabbedPane1.setEnabledAt(0, false);
        jTabbedPane1.setEnabledAt(1, true);
        jButtonSalvar.setVisible(true);
        jLabelCodigo.setVisible(false);
        jCodigo.setVisible(false);
        jEditar.setVisible(false);

    }//GEN-LAST:event_jButtonIncluirApartamentoActionPerformed

    private void JButtonVoltarMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonVoltarMenuPrincipalActionPerformed
        // TODO add your handling code here:
        new Inicial().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_JButtonVoltarMenuPrincipalActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        // TODO add your handling code here:
        int numero = 0, nroQuartos = 0, nroVagasGaragem = 0, anoConstrucao = 0, andar = 0, nroApt = 0;
        String logradouro = null, bairro = null, cidade = null, descricao = null, nomeEdificio = null;
        double areaTotal = 0, valor = 0, valorCondomio = 0;

        if (jNro.getText().trim().equals("") || jAndar.getText().trim().equals("") || jAnoContrucao.getText().trim().equals("")
                || jAreaTotal.getText().trim().equals("") || jBairro.getText().trim().equals("") || jDescricao.getText().trim().equals("")
                || jCidade.getText().trim().equals("") || jLogradouro.getText().trim().equals("") || jNroApt.getText().trim().equals("")
                || jNroQuartos.getText().trim().equals("") || jNroVagas.getText().trim().equals("") || jValor.getText().trim().equals("")
                || jValorCondominio.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Deve preencher todos os campos");
        } else {

            //<editor-fold defaultstate="collapsed" desc="Valores Setados">
            numero = Integer.parseInt(jNro.getText());
            nroQuartos = Integer.parseInt(jNroQuartos.getText());
            nroVagasGaragem = Integer.parseInt(jNroVagas.getText());
            anoConstrucao = Integer.parseInt(jAnoContrucao.getText());
            andar = Integer.parseInt(jAndar.getText());
            nroApt = Integer.parseInt(jNroApt.getText());
            logradouro = jLogradouro.getText();
            bairro = jBairro.getText();
            cidade = jCidade.getText();
            descricao = jDescricao.getText();
            nomeEdificio = jNomeEdificio.getText();
            areaTotal = Double.parseDouble(jAreaTotal.getText());
            valor = Double.parseDouble(jValor.getText());
            valorCondomio = Double.parseDouble(jValorCondominio.getText());
            //</editor-fold>

            Apartamento apartamento = new Apartamento(logradouro, numero, bairro, cidade, descricao, areaTotal,
                    valor, nroQuartos, nroVagasGaragem, anoConstrucao, nomeEdificio, andar, nroApt, valorCondomio);

            listaApartamento.incluir(apartamento);
            listaApartamento.escreverArquivo();

            //<editor-fold defaultstate="collapsed" desc="Limpar Campos">
            jCidade.setText("");
            jLogradouro.setText("");
            jNro.setText("");
            jBairro.setText("");
            jDescricao.setText("");
            jAreaTotal.setText("");
            jValor.setText("");
            jNroQuartos.setText("");
            jNroVagas.setText("");
            jAnoContrucao.setText("");
            jNomeEdificio.setText("");
            jAndar.setText("");
            jNroApt.setText("");
            jValorCondominio.setText("");
            //</editor-fold>

            int opcao = JOptionPane.showConfirmDialog(null, "Deseja inserir outro Apartamento?", "Imobiliária", JOptionPane.YES_NO_OPTION);
            if (opcao == JOptionPane.NO_OPTION) {
                jTabbedPane1.setSelectedIndex(0);
                jTabbedPane1.setEnabledAt(0, true);
                jTabbedPane1.setEnabledAt(1, false);
            }

        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarActionPerformed
        // TODO add your handling code here:
        //listaApartamento = lista.getLista();
        if (!(jTextCodigo.getText().trim().equals(""))) {
            listar(Integer.parseInt(jTextCodigo.getText().trim()), true);
        } else {
            listar(0, false);
        }


    }//GEN-LAST:event_jButtonListarActionPerformed

    //<editor-fold defaultstate="collapsed" desc="Método Para Apenas Inteiro">
    /**
     *
     * @param evt
     */
    private void apenasNumero(boolean ponto, java.awt.event.KeyEvent evt) {
        char caracter = evt.getKeyChar();
        
        if (ponto) {
            if (Character.isDigit(caracter) || caracter == '.') {

            } else {
                evt.consume();
            }    
        }else{
            if (Character.isDigit(caracter)) {

            } else {
                evt.consume();
            }    
        }
    }
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="Pegar Campo">
    private boolean pegarEVerificarCampo(javax.swing.JTextField campo) {
        String texto = campo.getText();
        for (int i = 0; i < texto.length(); i++) {
            if (texto.charAt(i) == '.') {
                return false;
            }

        }
        return true;
    }
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="Eventos - Campos Aceitando Apenas Números">
    private void jNroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jNroKeyTyped
        // TODO add your handling code here:
        apenasNumero(false,evt);
    }//GEN-LAST:event_jNroKeyTyped

    private void jValorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jValorKeyTyped
        // TODO add your handling code here:
        apenasNumero(true, evt);
    }//GEN-LAST:event_jValorKeyTyped

    private void jAreaTotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jAreaTotalKeyTyped
        // TODO add your handling code here:
        apenasNumero(pegarEVerificarCampo(jAreaTotal),evt);
    }//GEN-LAST:event_jAreaTotalKeyTyped

    private void jValorCondominioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jValorCondominioKeyTyped
        // TODO add your handling code here:
        apenasNumero(pegarEVerificarCampo(jValorCondominio), evt);
    }//GEN-LAST:event_jValorCondominioKeyTyped

    private void jAndarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jAndarKeyTyped
        // TODO add your handling code here:
        apenasNumero(false, evt);
    }//GEN-LAST:event_jAndarKeyTyped

    private void jNroAptKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jNroAptKeyTyped
        // TODO add your handling code here:
        apenasNumero(false, evt);
    }//GEN-LAST:event_jNroAptKeyTyped

    private void jNroVagasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jNroVagasKeyTyped
        // TODO add your handling code here:
        apenasNumero(false, evt);
    }//GEN-LAST:event_jNroVagasKeyTyped

    private void jAnoContrucaoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jAnoContrucaoKeyTyped
        // TODO add your handling code here:
        apenasNumero(false,evt);
    }//GEN-LAST:event_jAnoContrucaoKeyTyped

    private void jNroQuartosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jNroQuartosKeyTyped
        // TODO add your handling code here:
        apenasNumero(false,evt);
    }//GEN-LAST:event_jNroQuartosKeyTyped

    private void jTextCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextCodigoKeyTyped
        // TODO add your handling code here:
        apenasNumero(false,evt);
    }//GEN-LAST:event_jTextCodigoKeyTyped
    //</editor-fold>

    private void jButtonDetalhesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDetalhesActionPerformed
        // TODO add your handling code here:

        String codig = jList.getSelectedValue();

        Imovel a = listaApartamento.consultar(pegaCodigo(codig));
        if (a != null) {
            jTabbedPane1.setSelectedIndex(1);
            jTabbedPane1.setEnabledAt(0, true);
            jTabbedPane1.setEnabledAt(1, false);
            jButtonSalvar.setVisible(false);
            jLabelCodigo.setVisible(true);
            jCodigo.setVisible(true);

            Apartamento b = (Apartamento) a;
            jAndar.setText(String.valueOf(b.getAndar()));
            jCidade.setText(String.valueOf(b.getCidade()));
            jLogradouro.setText(String.valueOf(b.getLogradouro()));
            jNro.setText(String.valueOf(b.getNumero()));
            jBairro.setText(String.valueOf(b.getBairro()));
            jDescricao.setText(String.valueOf(b.getDescricao()));
            jAreaTotal.setText(String.valueOf(b.getAreaTotal()));
            jValor.setText(String.valueOf(b.getValor()));
            jNroQuartos.setText(String.valueOf(b.getNroQuartos()));
            jNroVagas.setText(String.valueOf(b.getNroVagasGaragem()));
            jAnoContrucao.setText(String.valueOf(b.getAnoConstrucao()));
            jNomeEdificio.setText(String.valueOf(b.getNomeEdificio()));
            jAndar.setText(String.valueOf(b.getAndar()));
            jValorCondominio.setText(String.valueOf(b.getValorCondominio()));
            jNroApt.setText(String.valueOf(b.getNroApt()));
            jCodigo.setText(String.valueOf(b.getCodig()));

            //<editor-fold defaultstate="collapsed" desc="Bloquear Campos">
            jNroQuartos.setEnabled(false);
            jAndar.setEnabled(false);
            jCidade.setEnabled(false);
            jLogradouro.setEnabled(false);
            jNro.setEnabled(false);
            jBairro.setEnabled(false);
            jDescricao.setEnabled(false);
            jAreaTotal.setEnabled(false);
            jValor.setEnabled(false);
            jNroQuartos.setEnabled(false);
            jNroVagas.setEnabled(false);
            jAnoContrucao.setEnabled(false);
            jNomeEdificio.setEnabled(false);
            jAndar.setEnabled(false);
            jValorCondominio.setEnabled(false);
            jNroApt.setEnabled(false);
            jCodigo.setEnabled(false);
            //</editor-fold>
        }


    }//GEN-LAST:event_jButtonDetalhesActionPerformed

    private void jListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListValueChanged
        // TODO add your handling code here:j

        if (jList.isSelectionEmpty()) {
            jButtonDetalhes.setEnabled(false);
            jButtonExcluir.setEnabled(false);
            jButtonEditar.setEnabled(false);
        } else {
            jButtonDetalhes.setEnabled(true);
            jButtonExcluir.setEnabled(true);
            jButtonEditar.setEnabled(true);

        }
    }//GEN-LAST:event_jListValueChanged

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        // TODO add your handling code here:
        String codig = jList.getSelectedValue();

        Imovel a = listaApartamento.consultar(pegaCodigo(codig));
        if (a != null) {
            jTabbedPane1.setSelectedIndex(1);
            jTabbedPane1.setEnabledAt(0, true);
            jTabbedPane1.setEnabledAt(1, false);
            jButtonSalvar.setVisible(false);
            jEditar.setVisible(true);
            jLabelCodigo.setVisible(true);
            jCodigo.setVisible(true);
            jCodigo.setEnabled(false);

            Apartamento b = (Apartamento) a;
            jAndar.setText(String.valueOf(b.getAndar()));
            jCidade.setText(String.valueOf(b.getCidade()));
            jLogradouro.setText(String.valueOf(b.getLogradouro()));
            jNro.setText(String.valueOf(b.getNumero()));
            jBairro.setText(String.valueOf(b.getBairro()));
            jDescricao.setText(String.valueOf(b.getDescricao()));
            jAreaTotal.setText(String.valueOf(b.getAreaTotal()));
            jValor.setText(String.valueOf(b.getValor()));
            jNroQuartos.setText(String.valueOf(b.getNroQuartos()));
            jNroVagas.setText(String.valueOf(b.getNroVagasGaragem()));
            jAnoContrucao.setText(String.valueOf(b.getAnoConstrucao()));
            jNomeEdificio.setText(String.valueOf(b.getNomeEdificio()));
            jAndar.setText(String.valueOf(b.getAndar()));
            jValorCondominio.setText(String.valueOf(b.getValorCondominio()));
            jNroApt.setText(String.valueOf(b.getNroApt()));
            jCodigo.setText(String.valueOf(b.getCodig()));
            aux = b.getCodig();

            //lista.editar(Integer.parseInt(codig), a);
        }
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditarActionPerformed

        // TODO add your handling code here:
        if (jNro.getText().trim().equals("") || jAndar.getText().trim().equals("") || jAnoContrucao.getText().trim().equals("")
                || jAreaTotal.getText().trim().equals("") || jBairro.getText().trim().equals("") || jDescricao.getText().trim().equals("")
                || jCidade.getText().trim().equals("") || jLogradouro.getText().trim().equals("") || jNroApt.getText().trim().equals("")
                || jNroQuartos.getText().trim().equals("") || jNroVagas.getText().trim().equals("") || jValor.getText().trim().equals("")
                || jValorCondominio.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Deve preencher todos os campos");
        } else {
            //Apartamento a = (Apartamento) lista.consultar(Integer.parseInt(jCodigo.getText().trim()));
            Apartamento apartamento = new Apartamento(jLogradouro.getText(), Integer.parseInt(jNro.getText()), jBairro.getText(), jCidade.getText(),
                    jDescricao.getText(), Double.parseDouble(jAreaTotal.getText()), Double.parseDouble(jValor.getText()), Integer.parseInt(jNroQuartos.getText()),
                    Integer.parseInt(jNroVagas.getText()), Integer.parseInt(jAnoContrucao.getText()), jNomeEdificio.getText(),
                    Integer.parseInt(jAndar.getText()), Integer.parseInt(jNroApt.getText()), Double.parseDouble(jValorCondominio.getText()));

            //a.setCidade(jCidade.getText());
            listaApartamento.editar(aux, apartamento);

            jTabbedPane1.setSelectedIndex(0);
            jTabbedPane1.setEnabledAt(1, false);
            jButtonDetalhes.setEnabled(false);
            jButtonExcluir.setEnabled(false);
            jButtonEditar.setEnabled(false);
            jButtonSalvar.setVisible(true);
            jEditar.setVisible(false);
            listar(0, false);

        }


    }//GEN-LAST:event_jEditarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // TODO add your handling code here:

        String codig = jList.getSelectedValue();
        int auxx = pegaCodigo(codig);
        listaApartamento.excluir(auxx);
        listar(0, false);
    }//GEN-LAST:event_jButtonExcluirActionPerformed
    /**
     *
     * @param codig Método para pegar apenas o Código da String da JList
     * @return
     */
    public int pegaCodigo(String codig) {
        int end = 0;
        for (int i = 0; i < codig.length(); i++) {
            if (codig.charAt(i) == '-') {
                end = i - 1;
                break;
            }
        }
        codig = codig.substring(0, end);
        return Integer.parseInt(codig);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApartamentoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApartamentoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApartamentoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApartamentoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApartamentoFrame(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonVoltarMenuPrincipal;
    private javax.swing.JTextField jAndar;
    private javax.swing.JTextField jAnoContrucao;
    private javax.swing.JTextField jAreaTotal;
    private javax.swing.JTextField jBairro;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonDetalhes;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonIncluirApartamento;
    private javax.swing.JButton jButtonListar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JTextField jCidade;
    private javax.swing.JTextField jCodigo;
    private javax.swing.JTextPane jDescricao;
    private javax.swing.JButton jEditar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JList<String> jList;
    private javax.swing.JTextField jLogradouro;
    private javax.swing.JTextField jNomeEdificio;
    private javax.swing.JTextField jNro;
    private javax.swing.JTextField jNroApt;
    private javax.swing.JTextField jNroQuartos;
    private javax.swing.JTextField jNroVagas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextCodigo;
    private javax.swing.JTextField jValor;
    private javax.swing.JTextField jValorCondominio;
    // End of variables declaration//GEN-END:variables
}
