/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.unipampa.frames;

/**
 *
 * @author luh-l
 */
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import org.unipampa.categorias.Imovel;
import org.unipampa.categorias.Terreno;
import org.unipampa.crud.ListaImoveisCrud;

public class TerrenoFrame extends javax.swing.JFrame {
    
    private ListaImoveisCrud listaTerreno;

    
    private DefaultListModel modelList = new DefaultListModel();
    
    private int aux;
    /**
     * Creates new form ChacaraFrame
     */
    public TerrenoFrame(ListaImoveisCrud listaTerreno) {
        initComponents();
        this.setLocationRelativeTo(null);
        
        this.listaTerreno = listaTerreno;

        Menu.setEnabledAt(1, false);
        Detalhes.setEnabled(false);
        Editar.setEnabled(false);
        Excluir.setEnabled(false);
    }
 public void listar(int cod, boolean isPesquisa) {
        DefaultListModel modelList = new DefaultListModel();
        
        if(isPesquisa){
            Imovel terreno = listaTerreno.consultar(cod);
            if(terreno == null){
                JOptionPane.showMessageDialog(null, "Imóvel não encontrado");
            }else {
                modelList.addElement(terreno.toString());
            }
        } else {
           List<Imovel> terr = listaTerreno.getLista();
            for (Imovel terreno : terr){
                modelList.addElement(terreno.toString());
            }
        }
        
        jList1.setModel(modelList); 
    }    
     public void excluir(int cod){
         listaTerreno.excluir(cod);
     }
     
    /**
     * Creates new form TerrenoFrame
     */
    public TerrenoFrame() {
        initComponents();
        this.setLocationRelativeTo(null);

        Menu.setEnabledAt(1, false);
    }
    private void apenasNumero(java.awt.event.KeyEvent evt){
        char caracter = evt.getKeyChar();
        if(Character.isDigit(caracter)){
            
        }else{
            evt.consume();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        codigo = new javax.swing.JTextPane();
        Listar = new javax.swing.JButton();
        Incluir = new javax.swing.JButton();
        Excluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        Voltar = new javax.swing.JButton();
        Detalhes = new javax.swing.JButton();
        Editar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Salvar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        Cancelar = new javax.swing.JButton();
        numero = new javax.swing.JTextField();
        cidade = new javax.swing.JTextField();
        logradouro = new javax.swing.JTextField();
        bairro = new javax.swing.JTextField();
        areaTotal = new javax.swing.JTextField();
        valor = new javax.swing.JTextField();
        dimensaoFrente = new javax.swing.JTextField();
        dimensaoLado = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        descricao = new javax.swing.JTextArea();
        jEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Terrenos");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Código:");

        jScrollPane11.setViewportView(codigo);

        Listar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Listar.setText("Listar");
        Listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarActionPerformed(evt);
            }
        });

        Incluir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Incluir.setText("Incluir");
        Incluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IncluirActionPerformed(evt);
            }
        });

        Excluir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Excluir.setText("Excluir");
        Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jList1);

        Voltar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Voltar.setText("Voltar");
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });

        Detalhes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Detalhes.setText("Detalhes");
        Detalhes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DetalhesActionPerformed(evt);
            }
        });

        Editar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Editar.setText("Editar");
        Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(290, 290, 290))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Detalhes)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(Excluir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                                        .addComponent(Incluir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Voltar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(45, 45, 45))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(Listar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Listar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(87, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Incluir)
                        .addGap(18, 18, 18)
                        .addComponent(Excluir)
                        .addGap(14, 14, 14)
                        .addComponent(Editar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Detalhes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Voltar)
                        .addGap(45, 45, 45))))
        );

        Menu.addTab("Menu", jPanel1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Logradouro:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Número:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Bairro:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Cidade:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Descrição:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Área Total:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Valor:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Dimensão Frente:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Dimensão Lado:");

        Salvar.setText("Salvar");
        Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarActionPerformed(evt);
            }
        });

        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        numero.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        numero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numeroKeyTyped(evt);
            }
        });

        cidade.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        logradouro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        bairro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        areaTotal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        areaTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                areaTotalKeyTyped(evt);
            }
        });

        valor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        valor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                valorKeyTyped(evt);
            }
        });

        dimensaoFrente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dimensaoFrente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dimensaoFrenteKeyTyped(evt);
            }
        });

        dimensaoLado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dimensaoLado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dimensaoLadoKeyTyped(evt);
            }
        });

        descricao.setColumns(20);
        descricao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        descricao.setRows(5);
        jScrollPane2.setViewportView(descricao);

        jEditar.setText("Editar");
        jEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(areaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(valor, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(logradouro, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                                            .addComponent(bairro)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 18, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dimensaoFrente, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(218, 218, 218)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dimensaoLado, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(logradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(117, 117, 117))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(areaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 50, Short.MAX_VALUE)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(dimensaoLado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dimensaoFrente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        Menu.addTab("Dados", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarActionPerformed
        
        String logradouro;
        int numero;
        String bairro;
        String cidade;
        String descricao;
        double areaTotal;
        double valor;
        double dimensaoFrente;
        double dimensaoLado;
        
        if (this.logradouro.getText().trim().equals("")|| this.numero.getText().trim().equals("") || this.bairro.getText().trim().equals("") || 
                this.cidade.getText().trim().equals("") || this.descricao.getText().trim().equals("")|| this.areaTotal.getText().trim().equals("") || 
                 this.valor.getText().trim().equals("")
                || this.dimensaoFrente.getText().trim().equals("") || this.dimensaoLado.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Deve preencher todos os campos");
        } else {
        logradouro = this.logradouro.getText();
        numero = Integer.parseInt(this.numero.getText());
        bairro = this.bairro.getText();
        cidade = this.cidade.getText();
        descricao= this.descricao.getText();
        areaTotal = Double.parseDouble(this.areaTotal.getText());
        valor = Double.parseDouble(this.valor.getText());
        dimensaoFrente = Double.parseDouble(this.dimensaoFrente.getText());
        dimensaoLado = Double.parseDouble(this.dimensaoFrente.getText());
        
        Imovel terreno = new Terreno(logradouro, numero, bairro, cidade, descricao, 
                areaTotal, valor, dimensaoFrente, dimensaoLado);
        
        listaTerreno.incluir(terreno);
        listaTerreno.escreverArquivo();
        
          JOptionPane.showMessageDialog(null, "Salvo Com Sucesso!");
            
           Menu.setSelectedIndex(0);

           Menu.setEnabledAt(0, true);
           Menu.setEnabledAt(1, false);
            
            this.logradouro.setText("");
            this.numero.setText("");
            this.bairro.setText("");
            this.cidade.setText("");
            this.descricao.setText("");
            this.areaTotal.setText("");
            this.valor.setText("");
            this.dimensaoFrente.setText("");
            this.dimensaoLado.setText("");      
    }//GEN-LAST:event_SalvarActionPerformed
    }
    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        Menu.setSelectedIndex(0);
        Menu.setEnabledAt(0, true);
        Menu.setEnabledAt(1, false);
        Salvar.setVisible(true);
        
        
         this.logradouro.setText("");
         this.numero.setText("");
         this.bairro.setText("");
         this.cidade.setText("");
         this.descricao.setText("");
         this.areaTotal.setText("");
         this.valor.setText("");
         this.dimensaoFrente.setText("");
         this.dimensaoLado.setText("");
         
         this.logradouro.setEnabled(true);
         this.numero.setEnabled(true);
         this.bairro.setEnabled(true);
         this.cidade.setEnabled(true);
         this.descricao.setEnabled(true);
         this.areaTotal.setEnabled(true);
         this.valor.setEnabled(true);
         this.dimensaoFrente.setEnabled(true);
         this.dimensaoLado.setEnabled(true);
         
    }//GEN-LAST:event_CancelarActionPerformed

    private void IncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IncluirActionPerformed
        Menu.setSelectedIndex(1);
        Menu.setEnabledAt(1, true);
        Menu.setEnabledAt(0, false);
        jEditar.setVisible(false);
    }//GEN-LAST:event_IncluirActionPerformed

    private void ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirActionPerformed
        String codigo = jList1.getSelectedValue();

        Imovel ii = listaTerreno.consultar(pegaCodigo(codigo));

        if (ii != null) {
            listaTerreno.excluir(pegaCodigo(codigo));
            JOptionPane.showMessageDialog(null, "Excluído com sucesso! ");

        }
     
    }//GEN-LAST:event_ExcluirActionPerformed

    private void ListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarActionPerformed
         if(!(codigo.getText().trim().equals(""))){
            listar(Integer.parseInt(codigo.getText().trim()), true);
        } else {
            listar(0, false);
        }
        
    }//GEN-LAST:event_ListarActionPerformed

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        new Inicial().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VoltarActionPerformed

    private void numeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numeroKeyTyped
        // TODO add your handling code here:
        apenasNumero(evt);
    }//GEN-LAST:event_numeroKeyTyped

    private void areaTotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_areaTotalKeyTyped
        // TODO add your handling code here:
         apenasNumero(evt);
    }//GEN-LAST:event_areaTotalKeyTyped

    private void valorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valorKeyTyped
        // TODO add your handling code here:
         apenasNumero(evt);
    }//GEN-LAST:event_valorKeyTyped

    private void dimensaoFrenteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dimensaoFrenteKeyTyped
        // TODO add your handling code here:
         apenasNumero(evt);
    }//GEN-LAST:event_dimensaoFrenteKeyTyped

    private void dimensaoLadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dimensaoLadoKeyTyped
        // TODO add your handling code here:
         apenasNumero(evt);
    }//GEN-LAST:event_dimensaoLadoKeyTyped

    private void DetalhesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DetalhesActionPerformed
        // TODO add your handling code here:
        Menu.setSelectedIndex(1);
        Salvar.setVisible(false);
        Menu.setEnabledAt(0, true);
        Menu.setEnabledAt(1, false);
        jEditar.setVisible(false);
        
        
        String codig = jList1.getSelectedValue();
        
       Imovel i = listaTerreno.consultar(pegaCodigo(codig));
       if (i != null) {

            Menu.setSelectedIndex(1);
            Menu.setEnabledAt(0, true);
            Menu.setEnabledAt(1, false);
        Terreno t = (Terreno)i;
        
       logradouro.setText(String.valueOf(t.getLogradouro()));
       numero.setText(String.valueOf(t.getNumero()));
       bairro.setText(String.valueOf(t.getBairro()));
       cidade.setText(String.valueOf(t.getCidade())); 
       descricao.setText(String.valueOf(t.getDescricao())); 
       areaTotal.setText(String.valueOf(t.getAreaTotal()));
       valor.setText(String.valueOf(t.getValor()));
       dimensaoFrente.setText(String.valueOf(t.getDimensaoFrente()));
       dimensaoLado.setText(String.valueOf(t.getDimensaoLado()));
       
       }
       
       logradouro.setEnabled(false);
       numero.setEnabled(false);
       bairro.setEnabled(false);
       cidade.setEnabled(false);
       descricao.setEnabled(false);
       areaTotal.setEnabled(false);
       valor.setEnabled(false);
       dimensaoFrente.setEnabled(false);
       dimensaoLado.setEnabled(false);
       
    }//GEN-LAST:event_DetalhesActionPerformed

    private void EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarActionPerformed
        // TODO add your handling code here:
        String codigo = jList1.getSelectedValue();
        
           Imovel ii = listaTerreno.consultar(pegaCodigo(codigo));

        if (ii != null) {
            Menu.setSelectedIndex(1);
            Menu.setEnabledAt(0, true);
            Menu.setEnabledAt(1, false);
            Salvar.setVisible(false);
            jEditar.setVisible(true);
            
            
        }

        Terreno tt = (Terreno) ii;

       logradouro.setText(String.valueOf(tt.getLogradouro()));
       numero.setText(String.valueOf(tt.getNumero()));
       bairro.setText(String.valueOf(tt.getBairro()));
       cidade.setText(String.valueOf(tt.getCidade())); 
       descricao.setText(String.valueOf(tt.getDescricao())); 
       areaTotal.setText(String.valueOf(tt.getAreaTotal()));
       valor.setText(String.valueOf(tt.getValor()));
       dimensaoFrente.setText(String.valueOf(tt.getDimensaoFrente()));
       dimensaoLado.setText(String.valueOf(tt.getDimensaoLado()));
       
       
        aux = tt.getCodig();
    }//GEN-LAST:event_EditarActionPerformed

    private void jEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditarActionPerformed
        // TODO add your handling code here:
        if (logradouro.getText().trim().equals("")|| numero.getText().trim().equals("") || bairro.getText().trim().equals("") || cidade.getText().trim().equals("") || descricao.getText().trim().equals("")|| areaTotal.getText().trim().equals("") || 
                 valor.getText().trim().equals("")
                || dimensaoFrente.getText().trim().equals("") || dimensaoLado.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Deve preencher todos os campos");
        } else {
         Terreno t = new Terreno (logradouro.getText(), Integer.parseInt(numero.getText()), bairro.getText(), 
                 cidade.getText(), descricao.getText(), Integer.parseInt(areaTotal.getText()),Integer.parseInt(valor.getText()) ,
                 Double.parseDouble(dimensaoFrente.getText()), Double.parseDouble(dimensaoLado.getText()));
         
         listaTerreno.editar(aux, t);
         Menu.setSelectedIndex(0);
         Menu.setEnabledAt(1, false);
         Detalhes.setEnabled(false);
         Salvar.setVisible(true);
         jEditar.setVisible(false);
         
        }
        
    }//GEN-LAST:event_jEditarActionPerformed

     public int pegaCodigo(String codig){
         int end = 0;
         for (int i = 0; i < codig.length(); i++) {
            if(codig.charAt(i) == '-'){
                end = i - 1;
                break;
            }
         }
         codig = codig.substring(0, end);
         return Integer.parseInt(codig);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TerrenoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TerrenoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TerrenoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TerrenoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TerrenoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JButton Detalhes;
    private javax.swing.JButton Editar;
    private javax.swing.JButton Excluir;
    private javax.swing.JButton Incluir;
    private javax.swing.JButton Listar;
    private javax.swing.JTabbedPane Menu;
    private javax.swing.JButton Salvar;
    private javax.swing.JButton Voltar;
    private javax.swing.JTextField areaTotal;
    private javax.swing.JTextField bairro;
    private javax.swing.JTextField cidade;
    private javax.swing.JTextPane codigo;
    private javax.swing.JTextArea descricao;
    private javax.swing.JTextField dimensaoFrente;
    private javax.swing.JTextField dimensaoLado;
    private javax.swing.JButton jEditar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField logradouro;
    private javax.swing.JTextField numero;
    private javax.swing.JTextField valor;
    // End of variables declaration//GEN-END:variables
}
